# ── Configuración local apuntando a Railway MySQL ─────────────
# Este archivo está en .gitignore — nunca lo subas al repositorio.

DB_URL=jdbc:mysql://kodama.proxy.rlwy.net:17894/railway?allowPublicKeyRetrieval=true&useSSL=false
DB_USERNAME=root
DB_PASSWORD=XsKrqDGZILCoFbhSvVKcpttpaETAHDEE
JWT_SECRET=matesaconcagua-produccion-clave-ultra-secreta-2025-minimo-32
MP_ACCESS_TOKEN=TEST-6014182034970530-051218-f573d6c96a85500e9de1ddb0332d6aa0-370981159
