spring.datasource.url=${DB_URL:jdbc:mysql://yamanote.proxy.rlwy.net:39372/railway?useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:adxAzfoVYmEtaohGVCYMiHEomLnWEDVi}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

server.port=${PORT:8080}

jwt.secret=${JWT_SECRET:matesaconcagua-clave-secreta-super-larga-minimo-32-caracteres}
jwt.expiration=86400000

mercadopago.access-token=${MP_ACCESS_TOKEN:APP_USR-3220136846990789-051218-4cd526d66d18cba1e095da0e77c06b40-3398128448}
