[build]
builder = "nixpacks"
buildCommand = "./mvnw clean package -Dmaven.test.skip=true"

[deploy]
startCommand = "java -jar target/*.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
